[package]
name = "spacegame_ui"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
bevy = { workspace = true, features = ["bevy_ui", "bevy_feathers", "bevy_picking"] }
thiserror = { workspace = true }
serde = { workspace = true }
spacegame_sim = { path = "../spacegame_sim" }
spacegame_data = { path = "../spacegame_data" }
